#------------------------------------------------------------------------------
# TravisCI configuration file for solidity.
#
# The documentation for solidity is hosted at:
#
# http://solidity.readthedocs.org
#
# ------------------------------------------------------------------------------
# This file is part of solidity.
#
# solidity is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# solidity is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with solidity.  If not, see <http://www.gnu.org/licenses/>
#
# (c) 2016-2017 solidity contributors.
#------------------------------------------------------------------------------

language: cpp
branches:
    # We need to whitelist the branches which we want to have "push" automation,
    # this includes tags (which are treated as branches by travis).
    # Pull request automation is not constrained to this set of branches.
    only:
        - develop
        - release
        - /^v[0-9]/

env:
    global:
        - ENCRYPTION_LABEL="6d4541b72666"
        - SOLC_BUILD_TYPE=RelWithDebInfo
        - SOLC_DOCS=Off
        - SOLC_EMSCRIPTEN=Off
        - SOLC_INSTALL_DEPS_TRAVIS=On
        - SOLC_RELEASE=On
        - SOLC_TESTS=On
        - SOLC_DOCKER=Off

matrix:
    include:
        # Ubuntu 14.04 LTS "Trusty Tahr"
        # https://en.wikipedia.org/wiki/List_of_Ubuntu_releases#Ubuntu_14.04_LTS_.28Trusty_Tahr.29
        #
        # TravisCI doesn't directly support any new Ubuntu releases.  These is
        # some Docker support, which we should probably investigate, at least for
        # Ubuntu 16.04 LTS "Xenial Xerus"
        # See https://en.wikipedia.org/wiki/List_of_Ubuntu_releases#Ubuntu_16.04_LTS_.28Xenial_Xerus.29.
        - os: linux
          dist: trusty
          sudo: required
          compiler: gcc
          env:
              - ZIP_SUFFIX=ubuntu-trusty

        - os: linux
          dist: trusty
          sudo: required
          compiler: clang
          env:
              - ZIP_SUFFIX=ubuntu-trusty-clang

        # Documentation target, which generates documentation using Phoenix / ReadTheDocs.
        - os: linux
          dist: trusty
          sudo: required
          compiler: gcc
          before_install:
            - sudo apt-get -y install python-sphinx 
          env:
              - SOLC_DOCS=On
              - SOLC_RELEASE=Off
              - SOLC_TESTS=Off
        # Docker target, which generates a statically linked alpine image
        - os: linux
          dist: trusty
          sudo: required
          services:
            - docker
          env:
            - SOLC_DOCKER=On
            - SOLC_INSTALL_DEPS_TRAVIS=Off
            - SOLC_RELEASE=Off
            - SOLC_TESTS=Off

        # Emscripten target, which compiles 'solc' to javascript and uploads the resulting .js
        # files to https://github.com/ethereum/solc-bin.  These binaries are used in Browser-Solidity
        # and in other Ethereum web-based development contexts.
        - os: linux
          dist: trusty
          sudo: required
          compiler: gcc
          node_js: "6"
          services:
              - docker
          before_install:
              - docker pull trzeci/emscripten:sdk-tag-1.35.4-64bit
          env:
              - SOLC_EMSCRIPTEN=On
              - SOLC_INSTALL_DEPS_TRAVIS=Off
              - SOLC_RELEASE=Off
              - SOLC_TESTS=Off

        # OS X Mavericks (10.9)
        # https://en.wikipedia.org/wiki/OS_X_Mavericks
        #
# Disabled because of problems on travis.
#        - os: osx
#          osx_image: beta-xcode6.2
#          env:
#              - ZIP_SUFFIX=osx-mavericks

        # OS X Yosemite (10.10)
        # https://en.wikipedia.org/wiki/OS_X_Yosemite
        #
#        - os: osx
#          osx_image: xcode7.1
#          env:
#              # Workaround for "macOS - Yosemite, El Capitan and Sierra hanging?"
#              # https://github.com/ethereum/solidity/issues/894
#              - TRAVIS_TESTS=Off
#              - ZIP_SUFFIX=osx-yosemite

        # OS X El Capitan (10.11)
        # https://en.wikipedia.org/wiki/OS_X_El_Capitan
        #
#        - os: osx
#          osx_image: xcode7.3
#          env:
#              # The use of Debug config here ONLY for El Capitan is a workaround for "The Heisenbug"
#              # See https://github.com/ethereum/webthree-umbrella/issues/565
#              - TRAVIS_BUILD_TYPE=Debug
#              # Workaround for "macOS - Yosemite, El Capitan and Sierra hanging?"
#              # https://github.com/ethereum/solidity/issues/894
#              - TRAVIS_TESTS=Off
#              - ZIP_SUFFIX=osx-elcapitan

        # macOS Sierra (10.12)
        # https://en.wikipedia.org/wiki/MacOS_Sierra
        #
#       - os: osx
#          osx_image: xcode8
#          env:
#              # Look like "The Heisenbug" is occurring here too, so we'll do the same workaround.
#              # See https://travis-ci.org/ethereum/solidity/jobs/150240930
#              - TRAVIS_BUILD_TYPE=Debug
#              # Workaround for "macOS - Yosemite, El Capitan and Sierra hanging?"
#              # https://github.com/ethereum/solidity/issues/894
#              - TRAVIS_TESTS=Off
#              - ZIP_SUFFIX=macos-sierra

git:
    depth: 2

cache:
    ccache: true
    directories:
        - boost_1_57_0
        - build
        - $HOME/.local

install:
    - test $SOLC_INSTALL_DEPS_TRAVIS != On || ./scripts/install_deps.sh
    - test "$TRAVIS_OS_NAME" != "linux" || ./scripts/install_cmake.sh
    - echo -n "$TRAVIS_COMMIT" > commit_hash.txt
    - test $SOLC_DOCKER != On || docker build -t ethereum/solc:build -f ./scripts/Dockerfile .
before_script:
    - test $SOLC_EMSCRIPTEN != On || ./scripts/build_emscripten.sh
    - test $SOLC_RELEASE != On || (./scripts/build.sh $SOLC_BUILD_TYPE
      && ./scripts/release.sh $ZIP_SUFFIX
      && ./scripts/create_source_tarball.sh )
script:
    - test $SOLC_DOCS != On || ./scripts/docs.sh
    - test $SOLC_TESTS != On || (cd $TRAVIS_BUILD_DIR && ./scripts/tests.sh )

deploy:
    # This is the deploy target for the Emscripten build.
    # It publishes the JS file which was compiled as part of the earlier 'build_emscripten.sh'
    # step to https://github.com/ethereum/solc-bin/tree/gh-pages/bin.
    # Both the build and deploy steps for Emscripten are only run within the Ubuntu
    # configurations (not for macOS).  That is controlled by conditionals within the bash
    # scripts because TravisCI doesn't provide much in the way of conditional logic.
   
    - provider: script
      script: test $SOLC_EMSCRIPTEN == On || scripts/release_emscripten.sh
      skip_cleanup: true
      on:
          branch:
            - develop
            - release
    # This is the deploy target for the dockerfile. If we are pushing into a develop branch, it will be tagged
    # as a nightly and appended the commit of the branch it was pushed in. If we are pushing to master it will
    # be tagged as "stable" and given the version tag as well.
    - provider: script
      script: test $SOLC_DOCKER != On || ./scripts/docker_deploy.sh
      skip_cleanup: true
      on:
          branch:
            - develop
            - release
    # This is the deploy target for the native build (Linux and macOS)
    # which generates ZIPs per commit and the source tarball.
    #
    # This runs for each tag that is created and adds the corresponding files.
    - provider: releases
      api_key:
          secure: PWH37xVBCF0XiSjl+eH7XIdkrfxZXjzvqF4PiBOnD3VnFz+odrdnIwBmCeBYTHTWF8efpp8fmzWJk2UVq1JcpyZiC+SVxO8dx91W2ia1a+wKrEQuDgkUrZBkl5IQNCv0QS81DDQhliyZEaYh8wHO/7RReyMpGpw2U2u85WkFiZ+LdlHEZPfzUeh9lxQ9n8qwFL8Rja+Q05d4cQ8zaVEtofJJT4T6DUWhc3TzuxDYxOmjwg37rC9CkGSLn6VadSh8b3j5R0SZupFsAEvBL/imBLP9r9ewoo7o4p6By3jwiIgH9yNg7LM618xbffcNaYF/KtLBi9uPHfqF7hRD4PlECz+D0PR78nQItOX5HKm1QMg5kCnghRVCA0IVjpV5fiYQnMLM7dCRv34I5b3zLpa69wQ/GLYB2FViqNUfvPeiZTEeIJ2OmATlFx8AH2JoqpY1XJknWb35+vMfa8LSiJJW++SLWeV+ncC92hrvyZ1cy3trepRRZIfyYepxHifnfdWMkddQUJk5b2WS5Fy/TJLZNPeombnpvRhUC38dsYItarKeXTc6k4oADCEDZ2rgGIcEiqRxXV11Y5xHJekLDWzUs+YJNcCuL4pnAP//LOnbnH2w9rLpwhQYSl0anCd097NivAXQJXO2JI/byIYz1kiCVQWnW6EM8+72mLOklf/Qr8k=

      overwrite: true
      file_glob: true
      file:
          - $TRAVIS_BUILD_DIR/solidity*.zip
          - $TRAVIS_BUILD_DIR/solidity*tar.gz
      skip_cleanup: true
      on:
          all_branches: true
          tags: true
          condition: $SOLC_RELEASE == On