#------------------------------------------------------------------------------
# Appveyor configuration file for solidity.
#
# The documentation for solidity is hosted at:
#
# http://solidity.readthedocs.org
#
# TODO - Tests currently disabled, because Tests-over-IPC code is using UNIX
# sockets unconditionally at the time of writing.
#
# ------------------------------------------------------------------------------
# This file is part of solidity.
#
# solidity is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# solidity is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with solidity.  If not, see <http://www.gnu.org/licenses/>
#
# (c) 2016 solidity contributors.
#------------------------------------------------------------------------------

branches:
  only:
    - release
    - develop
os: Visual Studio 2015
configuration:
    - RelWithDebInfo
# NB: Appveyor cache is disabled, because it is proving very unreliable.
# We can re-enable it when we find a way to mitigate the unreliability
# issues.  Have automated builds be reliable is the more important thing.
#cache: build
#
# In case we'd need a RDP detail to login into appveyor
#init:
#    - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
install:
    - git submodule update --init --recursive
    - scripts/install_deps.bat
    - set ETHEREUM_DEPS_PATH=%APPVEYOR_BUILD_FOLDER%\deps\install
before_build:
    - if not exist build mkdir build
    - cd build
    - cmake -G "Visual Studio 14 2015 Win64" .. -DTESTS=On
build_script:
    - msbuild solidity.sln /p:Configuration=%CONFIGURATION% /m:%NUMBER_OF_PROCESSORS% /v:minimal
    - cd %APPVEYOR_BUILD_FOLDER%
    - scripts\release.bat %CONFIGURATION%

test_script:
    - cd %APPVEYOR_BUILD_FOLDER%
    - cd deps\install\x64\eth
    - ps: $ethProc = Start-Process eth.exe --test
    - ps: Start-Sleep -s 100
    - cd %APPVEYOR_BUILD_FOLDER%\build\test\%CONFIGURATION%
    - copy "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\redist\x86\Microsoft.VC140.CRT\msvc*.dll" .
    - soltest.exe --show-progress -- --ipcpath \\.\pipe\geth.ipc

artifacts:
    - path: solidity-windows.zip
      name: solidity-windows-zip

# This is the deploy target for Windows which generates ZIPs per commit.
# We are in agreement that generating ZIPs per commit for the develop
# branch is probably just noise, so we only run this deployment target
# on 'release'.
#
# See https://www.appveyor.com/docs/deployment/github for information
# on GitHub Releases in Appveyor.
#
# You need to generate a GitHub personal access token for Appveyor
# See https://github.com/settings/tokens for more information on that.
# The token you generate there (in an encrypted form) is what is
# passed to this deployment target in the 'auth_token' parameter
# below.

deploy:
    provider: GitHub
    auth_token:
        secure: HPjiugbDSCsEFTphj/qwHuSw80/BV1xWoSvj95CPmtb16Ukh2VQbLVB7iFtZSans
    artifact: solidity-windows-zip
    on:
        branch: release
        appveyor_repo_tag: true

notifications:
    - provider: GitHubPullRequest
      on_build_success: false
      on_build_failure: false
      on_build_status_changed: false
