name: Docker Image [emscripten]

on:
  push:
    tags:
      - v*
      - emscripten-v*

jobs:
  build:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_DOCKER_REPOSITORY: docker.pkg.github.com/${{ github.repository }}
      IMAGE_NAME: emscripten

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          docker build ./docker --file docker/Dockerfile.$IMAGE_NAME --tag $IMAGE_NAME

      - name: Push image
        run: |
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          if [[ "${{ github.ref }}" == "refs/tags/"* ]]; then
            if [[ "$VERSION" =~ ^$IMAGE_NAME-v* ]]; then
              VERSION="$(echo $VERSION | sed -e "s/^$IMAGE_NAME-v//")-pre"
            elif [[ "$VERSION" =~ ^v* ]]; then
              VERSION="$(echo $VERSION | sed -e 's/^v//')"
            fi
          fi

          echo ${GITHUB_TOKEN} | docker login docker.pkg.github.com -u ${GITHUB_ACTOR} --password-stdin

          docker tag $IMAGE_NAME $GITHUB_DOCKER_REPOSITORY/$IMAGE_NAME:$VERSION
          docker push $GITHUB_DOCKER_REPOSITORY/$IMAGE_NAME:$VERSION

          docker logout

